- README.md
- REQUIRE
- examples/01-hello-impl.jl
- examples/01-hello.jl
- examples/02-broadcast-impl.jl
- examples/02-broadcast.jl
- examples/03-reduce-impl.jl
- examples/03-reduce.jl
- examples/04-sendrecv-impl.jl
- examples/04-sendrecv.jl
- examples/05-juliacman.jl
- src/MPI.jl
- src/cman.jl
- src/mpi-base.jl
Allows for an mpi cluster to be started from the julia master. Hence makes it possible for julia parallel methods to be used along with code making MPI calls.
> added cluster manager for mpi

- REQUIRE
- deps/build.jl
- examples/02-broadcast-impl.jl
- examples/05-juliacman.jl
- examples/06-cman-transport.jl
- src/MPI.jl
- src/cman.jl
Not that right now this pr includes the commit from #80
> Fix some deprecations and add Compat dependency

- deps/build.jl
> Accept more environment variables to specify cmake options

- src/cman.jl
> @mpi_do prints remote exceptions if present

- conf/travis-install-mpi.sh
Should fix https://github.com/JuliaParallel/MPI.jl/issues/87
> Install an updated gcc

- src/mpi-base.jl
This fixes a conflict between #89 and #90.
> fix conflict between #89 and #90

- src/mpi-base.jl
- test/test_allgather.jl
- test/test_gather.jl
`Allgather` and `Gather` were returning the wrong things if you gave them objects instead of arrays. I added tests for them.
> Fix all/gather bugs and add tests

- src/MPI.jl
This seems to cure the segfault on Ubuntu 15.10.
Fixes #25.
> Don't use RTLD_DEEPBIND

- .travis.yml
- conf/travis-install-mpi.sh
The link to the MPICH 3 package is dead and I couldn't find a new for Precise so I decided to try out Travis' Trusty version.
> Try using trusty

- src/mpi-base.jl
Also avoid some temporary arrays.
> Make Test / Wait routines more type-stable

- src/mpi-base.jl
Allow the user to pass a Ref along with Ptr and Array to routines for instance
```
sreq = MPI.Isend(Ref(x, 4), cnt, dest, tag, comm)
```
which is safer than
```
sreq = MPI.Isend(pointer(x, 4), cnt, dest, tag, comm)
```
Since the buffer type was getting long (and possibly hard to maintain for future types), I aliased the buffer type as well.
> Adding MPIBuffertype and allow for Ref{T}

- src/mpi-base.jl
- test/test_wait.jl
I didn't expect to submit another PR so soon, but I discovered the `Waitany!`function is broken.  This fixes it and adds a test.
> Waitany fix

- src/win_mpiconstants.jl
- test/test_datatype.jl
- test/test_sendrecv.jl
For `type_create` and for `Testall!`
> Two little tests

- src/cman.jl
> support introduction of cookie in master

- README.md
Since this seems to be tripping many people up.
> Add a note to README about Windows wrapping.

- src/cman.jl
- src/mpi-base.jl
`cell -> Array(Any)`
Correct the version test for `fieldoffsetts`
> A few fixes for Julia 0.5.

- conf/travis-install-mpi.sh
These seemed to work in my tests
> Update build script to fix Mac CI

- conf/travis-install-mpi.sh
Reverts JuliaParallel/MPI.jl#181
> Revert "Update build script to fix Mac CI"

- .travis.yml
- conf/travis-install-mpi.sh
- src/cman.jl
- test/runtests.jl
- test/test_cman_julia.jl
As discussed in PR #201. I will also add the cman test fixes here if the problems are confirmed in the CI output.
> Upgrade linux mpich and open-mpi versions

- README.md
- deps/CMakeLists.txt
- deps/gen_functions.c
- src/mpi-base.jl
- src/win_mpiconstants.jl
- test/test_onesided.jl
Adds two more one-sided comms functions, which I need for an experimental array library.
> Add onesided accumulate functions

- src/mpi-base.jl
I'm teaching a class right now using `MPI.jl` and have documented some of the `MPI.jl` functions for my students. This is far from complete, but wanted to contribute them back to the package.
> Docs for `Isend`, `Irecv!`, `send`, `recv!` `Wait!`, `Waitany!, and `Waitall!`

- docs/make.jl
I forgot to uncomment this in #241.
> deploy docs

- .travis.yml
- conf/travis-install-mpi.sh
just a small refactor that makes the test a bit by a minute or so since we only run Coverage once.
> cleanup .travis

- deps/CMakeLists.txt
I still don't really understand how CMake works, but this doesn't appear to be used.
> remove unused part from CMake file

- deps/build.jl
- src/MPI.jl
- src/deprecated.jl
- src/mpi-base.jl
- src/mpi-window.jl
- src/win_mpiconstants.jl
- test/test_onesided.jl
- test/test_shared_win.jl
- use keyword splatting of arguments into Info objects
- add refcount tracking
- create/allocate functions create new `Win` objects
- make Win_free a method of free
- move to new file
- deprecation of old interface
> Update Window functions

- .travis.yml
> allow failures on OS X with openmpi

- src/mpi-base.jl
> Fix typo in docs for MPI.Send method

- .appveyor.yml
- src/cman.jl
- src/info.jl
- src/operators.jl
- test/runtests.jl
- test/test_allreduce.jl
- test/test_reduce.jl
> Disable custom reduction operators on Windows

- .appveyor.yml
- .travis.yml
- deps/build.jl
- docs/src/installing.md
- src/cman.jl
- test/runtests.jl
- test/test_cman_julia.jl
> Define mpiexec variable at build time

- src/MPI.jl
Work around https://github.com/openucx/ucx/issues/4001
@simonbyrne can you check that this fully fixes your issue?
> disable UCX memory hooks

- .gitlab-ci.yml
- Project.toml
- docs/src/usage.md
- src/MPI.jl
- src/collective.jl
- src/cuda.jl
- src/datatypes.jl
- src/pointtopoint.jl
- src/window.jl
- test/cudaenv/Project.toml
- test/test_allgather.jl
- test/test_allgatherv.jl
- test/test_allreduce.jl
- test/test_alltoall.jl
- test/test_alltoallv.jl
- test/test_bcast.jl
- test/test_exscan.jl
- test/test_gather.jl
- test/test_gatherv.jl
- test/test_onesided.jl
- test/test_reduce.jl
- test/test_scan.jl
- test/test_scatter.jl
- test/test_scatterv.jl
- test/test_sendrecv.jl
- test/test_spawn.jl
- test/test_test.jl
- test/test_wait.jl
This incorporates @kose-y's  changes from #286 (squashed) along with tests.
I needed to open a new PR to trigger the Gitlab buildbot.
> CUDA-aware MPI with tests

- src/environment.jl
> Throw more informative error if MPI.Init() is called multiple times

- src/topology.jl
- test/test_cart_get.jl
This includes docs and tests. Local tests pass.
> WIP: add wrapper to `Cart_get`

- test/test_cart_create.jl
- test/test_cart_shift.jl
> reenable Finalized tests

- .appveyor.yml
- .gitlab-ci.yml
- .travis.yml
- test/test_allgather.jl
- test/test_allgatherv.jl
- test/test_allreduce.jl
- test/test_alltoall.jl
- test/test_alltoallv.jl
- test/test_bcast.jl
- test/test_exscan.jl
- test/test_gather.jl
- test/test_gatherv.jl
- test/test_reduce.jl
- test/test_scan.jl
- test/test_scatter.jl
- test/test_scatterv.jl
- test/test_sendrecv.jl
- test/test_test.jl
- test/test_wait.jl
remove use of Pkg.installed() to check for CuArrays
> Add Julia 1.3 to test matrix

- deps/build.jl
> Improve no MPI error

- deps/build.jl
- docs/src/installation.md
- test/runtests.jl
> add JULIA_MPIEXEC_ARGS env variable

- docs/src/environment.md
- docs/src/installation.md
- docs/src/usage.md
- src/cuda.jl
- src/environment.jl
- test/test_basic.jl
> expose interface to check CUDA support

- src/environment.jl
> Spectrum MPI, does not have MPIX_Query_cuda_support

- docs/make.jl
- docs/src/environment.md
- docs/src/installation.md
- docs/src/library.md
- docs/src/topology.md
- src/environment.jl
- src/implementations.jl
- test/test_threads.jl
Expose `MPI_Query_thread` and `MPI_Is_thread_main`, along with some doc cleanup.
> Additional threading functions and docs

- .github/workflows/Documenter.yml
- .travis.yml
- README.md
- deps/build.jl
- docs/make.jl
- test/runtests.jl
Travis docs don't seem to be building, so it probably makes sense to move to GitHub Actions.
> Move docs to GitHub Actions

- test/runtests.jl
* remove the `runtests` function
* remove the `nfail` variable cruft
* generate a testset for each included file
* do a dummy `@test true` for each test in the loop: if the process errors out
the testset would error out as well
> Simplifiy tests infrastructure

- docs/src/io.md
- src/io.jl
- test/test_io.jl
> Clean up I/O tests to only use MPI I/O

- docs/src/knownissues.md
Addresses #398.
cc @amartinhuertas
> Document compilecache race condition issue and fix

- .travis.yml
- deps/build.jl
- src/environment.jl
- test/runtests.jl
> Switch JULIA_MPIEXEC_ARGS back to runtime and apply if JLL is used

- docs/examples/03-reduce.jl
> Update Reduce example to use custom datatypes and operators

- deps/build.jl
can call Pkg.build("MPI") without triggering another round of precompilation
> only update deps.jl if MPI has changed

- src/environment.jl
> add function to call init hooks

- test/test_shared_win.jl
> Remove unnecessary views

- docs/examples/05-job_schedule.jl
- docs/make.jl
Hi,
I've built an example where you want to apply a function to an array of data with job scheduling. This example is inspired on https://www.hpc.ntnu.no/ntnu-hpc-group/vilje/user-guide/software/mpi-and-mpi-io-training-tutorial/basic-mpi/job-queue
> Add new example to docs

- src/operators.jl
The error thrown by Julia when getting to closures unsupported on non-Intel
platforms is like this:
```
ERROR: LoadError: cfunction: closures are not supported on this platform
in expression starting at /path/to/file.jl:line
```
and nothing else, without a full stacktrace, but `/path/to/file.jl:line` is only
the top-level frame of the stack.  It can take a while to understand where the
error is actually coming from especially if several packages are involved,
provided that you're willing to debug it, otherwise users are out of luck.
> Throw an error when using custom reductions on non-Intel platforms

- test/test_io_shared.jl
We are getting intermediate failures, hopefully this fixes it.
> Add a bunch of barriers to io_shared tests

- .github/workflows/UnitTests.yml
MPICH 3.4 should have fixed https://github.com/pmodels/mpich/issues/4710
> Remove MacOS workarounds

- src/datatypes.jl
- test/test_datatype.jl
> Make `show` on Datatype functional before MPI has been initialized

- src/deprecated.jl
- src/nonblocking.jl
- test/runtests.jl
- test/test_test.jl
I accidentally disabled these in #496.
> fix runtests

- src/datatypes.jl
> Add bool datatype handling

- src/implementations.jl
> fix MPICH version string capture

- docs/src/topology.md
- src/deprecated.jl
- src/topology.jl
- test/test_cart_coords.jl
- test/test_cart_create.jl
- test/test_cart_get.jl
- test/test_cart_rank.jl
- test/test_cart_shift.jl
- test/test_dims_create.jl
- test/test_sendrecv.jl
Fixes #533, also gets rid of mutating functions: they're not really that useful, and the make the API confusing.
> clean up Cartesian topology functions

- .github/workflows/PreviewCleanup.yml
- docs/Project.toml
- docs/make.jl
- docs/src/mpipreferences.md
- lib/MPIPreferences/src/MPIPreferences.jl
- Add docs and warning to MPIPreferences
- add PreviewCleanup
> Add docs for MPIPreferences

- lib/MPIPreferences/src/MPIPreferences.jl
> openmpi needs to be opened with RTLD_GLOBAL

- docs/src/configuration.md
- src/MPI.jl
- test/mpiexecjl.jl
- test/runtests.jl
- Re-export use_jll_binary and use_system_binary
- Rewrite configuration docs for MPIPreferences
> Rewrite configuration docs for MPIPreferences

- .buildkite/pipeline.yml
- src/cuda.jl
- test/runtests.jl
- test/test_bcast.jl
- Improve CUDA-aware MPI support and add CI
- test hypothesis
> Enable GPU CI

- .github/workflows/UnitTests.yml
Ref: https://github.com/JuliaParallel/MPI.jl/pull/572#issuecomment-1128869416
> Use MPIWrapper 2.8.1 in CI

- src/consts/microsoftmpi.jl
- src/consts/mpich.jl
- src/consts/mpitrampoline.jl
- src/consts/mpt.jl
- src/consts/openmpi.jl
See https://github.com/JuliaParallel/MPI.jl/pull/597.
> Support MPI_WEIGHTS_EMPTY for MPItrampoline

- docs/src/reference/environment.md
- lib/MPIPreferences/src/MPIPreferences.jl
- lib/MPIPreferences/src/system.jl
- src/MPI.jl
- src/error.jl
Extracted from #597
cc @giordano @eschnett
> add version errors

- src/comm.jl
- test/test_comm.jl
Fixes #579.
Needs a test.
cc: @omlins
> add SplitType

- Project.toml
- lib/MPIPreferences/Project.toml
#602 added `libmpi_handle` to MPIPreferences.System module
> bump MPIPreferences

- lib/MPIPreferences/Project.toml
This is to publish changes in #614.
> Release v0.1.4 of `MPIPreferences`

- src/MPI.jl
> add warning if JULIA_MPI_BINARY is inconsistent with MPIPreferences

- docs/src/reference/pointtopoint.md
- src/nonblocking.jl
- src/pointtopoint.jl
- test/test_cart_shift.jl
- test/test_ibarrier.jl
- test/test_sendrecv.jl
- test/test_test.jl
> add PROC_NULL, ANY_SOURCE, ANY_TAG as globals

- docs/src/configuration.md
- lib/MPIPreferences/src/MPIPreferences.jl
Closes #661 and #599.
Since it was almost as difficult to write down what I had in mind for a transition guide as writing the guide itself, I tried to draft a first version of the guide. Please let me know what you think.
> Transition guide from v0.19 and earlier to v0.20+

- .github/workflows/UnitTests.yml
Check that #561 is now fixed in Julia 1.8
> check if MPI tests select correct implementation

- Project.toml
- docs/src/reference/pointtopoint.md
- lib/MPIPreferences/Project.toml
Bump versions MPIPreferences.jl and MPI.jl
Also remove some unlinked lines from the doc.
> bump versions

- README.md
> Add note on breaking changes in v0.20

- .buildkite/pipeline.yml
> AMDGPU does not work on Julia 1.8, so test on nightly

- Project.toml
- docs/src/reference/pointtopoint.md
- src/pointtopoint.jl
- test/test_persistent.jl
These are helpful to avoid allocations in creating request objects (#643)
> add support for persistent requests

- docs/examples/04-sendrecv.jl
- docs/examples/05-job_schedule.jl
- src/deprecated.jl
- src/nonblocking.jl
- src/pointtopoint.jl
- test/test_ibarrier.jl
Matches the changes in #479, for some reason I missed these functions in that PR.
> make Status args to Probe/Iprobe optional

- .github/workflows/UnitTests.yml
- test/mpiexecjl.jl
- test/test_spawn.jl
This should in principle avoid running in https://github.com/JuliaLang/julia/issues/48039, but locally I'm still seeing the same problem :confused:
> Consistently use `Base.julia_cmd()` in tests

- docs/make.jl
- docs/src/configuration.md
- docs/src/external.md
- docs/src/reference/comm.md
- docs/src/reference/environment.md
- src/environment.jl
> Add section on external libraries

- src/buffers.jl
- src/datatypes.jl
- src/deprecated.jl
- src/operators.jl
- test/test_allreduce.jl
> define operators for logical types

- test/test_threads.jl
Branched right off Tag 0.20.8 in which all tests were passing.
> Test GC in multi-thread code

- .github/workflows/UnitTests.yml
> Fix some CI failures

- src/implementations.jl
Make `versioninfo` behave similar to what is done in InteractiveUtils, CUDA, AMDGPU, ...
> Add optional io argument to versioninfo()

- .buildkite/pipeline.yml
- docs/src/configuration.md
Clean up the Buildkite yml file and update the config doc wrt #764
> Cleanup and update doc

- Project.toml
- test/Project.toml
Upgrade to minor version upgrade of AMDGPU that fixes TLS device handling
> Bump AMDGPU compat

- docs/src/usage.md
Suggested fix for https://github.com/JuliaParallel/MPI.jl/issues/786
> docs: usage of mpiexec()

- src/api/api.jl
- test/test_comm.jl
> add c2f/f2c handle conversions

- src/topology.jl
> More typos

- Project.toml
- test/Project.toml
Bump compat to latest 0.8 release.
> AMDGPU compat

- docs/src/knownissues.md
Adding clarification following this discussion:
https://discourse.julialang.org/t/openmpi-threading-segfault-in-compilation/105881/7?u=mmesiti
> known issues: further clarification regarding UCX_ERROR_SIGNALS

- .github/workflows/UnitTests.yml
Ref: https://github.com/JuliaParallel/MPI.jl/pull/834#issuecomment-2165801463
> [CI] Update MPIWrapper to v2.11.0

- src/MPI.jl
To help with: https://github.com/JuliaParallel/MPI.jl/issues/846#issuecomment-2203882843
> set environment variables before dlopen

- Project.toml
- test/Project.toml
Addresses #860 also including test
> Bump AMDGPU

- test/runtests.jl
- test/test_gather.jl
> Add a test checking number of ranks is correct
