README.md
src/cman.jl

support cman MPICH, replace "tail -f" for STDOUT redirection with a reverse socket connection
Closes #33
Closes #30

support cman MPICH, replace "tail -f" for STDOUT redirection 

---

README.md
examples/02-broadcast-impl.jl
examples/04-sendrecv-impl.jl
examples/05-juliacman.jl
examples/06-cman-transport.jl
src/cman.jl
src/mpi-base.jl

....to have all processes part of both the MPI as well as Julia clusters.

Cluster Manager supports all processes as part of MPI. Also allows for MPI as a transport option.

---

examples/07-pi.jl
examples/montecarlo.jl

montecarlo.jl is a framework for simple Monte Carlo using MPI-only mode. This can serve as an example of MPI usage for beginners, but it's also a framework that can be adapted easily to do work of real interest. 07-pi.jl is an example of approximating pi which uses the framework.

add montecarlo-jl and example

---

src/mpi-base.jl
test/runtests.jl
test/test_allgather.jl
test/test_allgatherv.jl
test/test_alltoall.jl
test/test_alltoallv.jl
test/test_bcast.jl
test/test_exscan.jl
test/test_gather.jl
test/test_gatherv.jl
test/test_reduce.jl
test/test_scan.jl
test/test_scatter.jl
test/test_scatterv.jl
test/test_sendrecv.jl

This changes `runtests.jl` to use the full path to the test files. They often failed for me because of this.

Fix deprecation warnings and tests.

---

README.md
deps/build.jl

Check the environment variables JULIA_MPI_INCLUDE_PATH and JULIA_MPI_LIBRARIES to allow overriding cmake's detection of MPI.
This is e.g. currently necessary with OpenMPI, since current versions of cmake don't autodetect the Fortran libraries correctly.

Allow overriding cmake's MPI detection via environment variables 

---

deps/CMakeLists.txt

Once these cmake policies will become unsupported, we will receive errors instead of silent breakage.

Set cmake policies to avoid cmake warnings

---

test/runtests.jl

Right now the actual error messages are suppressed because of `success`, but I think it would be useful to get some output from failed tests. All tests are still run because of the try/catch block.

Make some informative output when tests fail

---

deps/build.jl

Old builds can often cause trouble so I routinely delete these manually and thought it would make sense to automate the process.

Delete build and usr directories if they exist when calling Pkg.build

---

deps/CMakeLists.txt
deps/gen_functions.c
src/mpi-base.jl
test/test_basic.jl

Because MPI.jl uses the Fortran interface, it is a bit challenging to use with a library like PETSc that relies on the C MPI interface.   In particular, PETSc and similar libraries require you to supply a C `MPI_Comm` object, which in general is a different type than the Fortran object (just a `Cint`).  This PR rectifies the situation by adding an `MPI.CComm` type and ~~functions `MPI.Comm2C` and `MPI.C2Comm`~~ `convert` methods to convert between that and the `Comm` type.
If/when #59 is addressed, these functions can become no-ops.
cc: @JaredCrean2

add MPI.CComm type for interoperability with the C API

---

src/mpi-base.jl

The Julia MPI package always uses Int instead of Cint.

Ensure that the Get_* functions return Int

---

examples/05-juliacman.jl
examples/06-cman-transport.jl
src/cman.jl
test/runtests.jl
test/test_cman_julia.jl
test/test_cman_mpi.jl
test/test_cman_tcp.jl

Rename some functions for clarity.
Add many comments.
Clean up / correct termination handling.
Avoid blocking MPI communication in example.
Add test cases.

Restructure MPI cluster manager

---

README.md
deps/build.jl

Some of these are now necessary since `MPI.jl` started using the MPI C interface, and requires the respective settings in `CMakeLists.txt`.

Support additional cmake configuration variables

---

src/cman.jl
test/test_cman_julia.jl

and don't run `localize_vars` on the expression. This is similar to how @everywhere evaluates.

Evaluate expressions in @mpi_do in Main module

---

README.md

For a class I am teaching I put together some info on the MPI-only interface (particularly a list of all the functions currently wrapped).
Take it or leave it, but thought it might be a useful bit of info for the project README

Adding info on the wrapped MPI functions

---

src/mpi-base.jl
src/win_mpiconstants.jl
test/test_sendrecv.jl

The Cancel function was broken in multiple ways. It's fixed now,
with a small test.

Fix bug and add test for Cancel

---

.travis.yml
conf/travis-install-mpi.sh

I had to do the same thing in https://github.com/JuliaParallel/Elemental.jl/blob/master/mpi.sh. OpenMPI 1.6.x is old and broken but only the development version of Ubuntu seems to have a more recent version so we'll have download and build OpenMPI.

Test with a non-broken OpenMPI

---

test/runtests.jl

The appveyor test right now fail because the first test starts multiple julia instances that all try to precompile MPI at the same time. This PR will trigger the precompile before any new processes are started and thus fixes that bug.

Add using MPI as first command in test to precompile

---

src/mpi-op.jl
test/test_reduce.jl

This fixes a bug where `opfunc` is incorrectly passed to `Reduce`.

Pass opfunc correctly to Reduce

---

.travis.yml
REQUIRE
appveyor.yml
src/cman.jl
src/mpi-base.jl
test/test_datatype.jl

This pull request fixes those depwarns under 0.7 that can be fixed without breaking 0.6. Best!

fix various depwarns under 0.7 (without breaking 0.6)

---

src/win_mpiconstants.jl

Is there a reason why it was not defined here?

Add MPI_ABORT to win_mpiconstants

---

src/mpi-base.jl

Since using SubArrays has become quite comfortable due to the views macro and seems to be encouraged by many Julia devs, it would be great, if they would be directly supported by MPI (i.e. without creating a reference to the subarray first)
@views begin
sreq = MPI.Isend(arr[range1], dest, tag, comm)`
rreq = MPI.Irecv!(arr[range2], src, tag, comm)`
end
This would actually only require adding SubArray to MPIBuffertype.
`MPIBuffertype{T} = Union{Ptr{T}, Array{T}, SubArray{T}, Ref{T}}`
However SubArrays can contain non-contiguous memory blocks, whereas MPI assumes contiguous memory. I wanted to have routines providing convenience interfaces for Array to also support SubArrays. The checks whether a SubArray is contiguous are placed only in these convenience functions, which I intended to be …

Add support for SubArrays

---

README.md
deps/CMakeLists.txt
deps/juliampi.c
src/mpi-base.jl
test/runtests.jl
test/test_basic.jl
test/test_finalize_atexit.jl

This is useful for enabling cleanup using standard Julia finalizers, which otherwise run after `MPI.Finalize()`.

Optionally call MPI.Finalize at exit

---

src/MPI.jl
src/mpi-base.jl

This turns the symbol names into references, and fills in the handles at `__init__` time. Without this, there were precompilation warnings when precompiling a module using MPI.jl on Julia 1.0.

Support for precompiling modules based on MPI.jl

---

conf/travis-install-mpi.sh
src/cman.jl

Hi All - another PR. This one addresses a problem I have run into launching ```MPI.jl``` in ```mode != MPI_TRANSPORT_ALL``` style with julia 1.0.1 and 1.0.2 on a multi-node cluster. 
As described below it looks to me that a change in ```julia/stdlib/Sockets/src/Sockets.jl``` about a year ago may have impacted the ability of ```MPI.jl``` to start up in some use cases on multi-node cluster setups?
This PR addresses a side-effect of [a security/semantics issue](https://github.com/JuliaLang/julia/pull/23699) that was [fixed](https://github.com/JuliaLang/julia/commit/775f1fc42622b3a141aa242ffe04c22eb08dfdd9 ) a year ago in core library [```julia/stdlib/Sockets/src/Sockets.jl```](https://github.com/JuliaLang/julia/blob/96ce5ba22122280b67991849acdb17b36603224f/stdlib/Sockets/src/Sockets.jl#L577). …

Add MPImanager option to address side effect of https://github.com/JuliaLang/julia/pull/23699

---

README.md

The rules followed by CMake to find the path to compilers are not immediate. This PR adds a few hints in the README.

Add an explanation about compilers' detection

---

README.md
appveyor.yml
deps/gen_functions.c
src/MPI.jl
src/mpi-base.jl
src/mpi-op.jl
src/win_mpiconstants.jl
test/test_allgather.jl
test/test_allgatherv.jl
test/test_allreduce.jl
test/test_alltoall.jl
test/test_alltoallv.jl
test/test_gather.jl
test/test_gatherv.jl
test/test_reduce.jl
test/test_scatter.jl
test/test_scatterv.jl

(This is a fixed [#230](https://github.com/JuliaParallel/MPI.jl/pull/230).)
Hi, 
I would like to implement non allocating versions for several MPI operations, as well as support for  MPI_IN_PLACE.
This PR defines a new variable, MPI.IN_PLACE of type `Ptr{Cvoid}`, and refactors the code of the following functions to implement a non-allocating version which accepts `MPI.IN_PLACE` if supported by MPI.
For the following functions, calling `MPI_IN_PLACE` is slightly less straightforward, so I felt that the best way to support it would be to create a new method called `XXX_in_place!`. 
If you think this is not a good idea, feel free to propose a better solution.
The last three functions listed above are still missing, and if you are interested I'll be glad to include them in the PR.
I believe …

Implement MPI_IN_PLACE for MPI Operations

---

src/MPI.jl

As @simonbyrne pointed out, it seems that
https://github.com/JuliaParallel/MPI.jl/blob/bc2e97949aae507414c96c4596961f0d05abc3e5/src/mpi-op.jl#L27
returns a `Char` on Windows 32 bit when it should (?) be an `Int32`.
To avoid this we make sure the inverse map doesn't contain the value `Char`.

Work around a type issue on Windows 32 bit

---

docs/src/installing.md

JULIA_MPI_Fortran_INCLUDE_PATH is a path to the include directory for mpif90 (not a flag passed to the compiler), so it doesn't need the "-I" at the start

JULIA_MPI_Fortran_INCLUDE_PATH doesn't need -I

---

src/MPI.jl
src/mpi-base.jl
src/mpi-info.jl
test/test_info.jl

This avoids relying on the gfortran ABI for strings. Also a good test case for moving to the C API generally.

move Info to C interface

---

deps/consts_msmpi.jl
deps/gen_consts.jl
src/comm.jl
test/runtests.jl
test/test_universe_size.jl

As part of development of MPIExecutor.jl, a package inspired by mpi4py that I'm working on, I need to be able to get the universe size to provide sane defaults.

Add Universe_size

---

deps/build.jl
deps/gen_consts.jl

This makes it slightly easier to use on clusters since it avoids the need to "module load mpiXXX" each time it is used, and makes it more robust if the wrong MPI library is loaded.
Also improves the error message if no MPI library is found.

Store full path of libmpi and mpiexec in deps.jl

---

src/collective.jl

Fixes #283. 
No other file doing such assertion.

size check only for AbstractArrays on collective.jl

---

src/cman.jl
test/test_cman_mpi.jl

Remotecalls over MPI Transport between workers will call `get` on an integer that represents the target's id. This change removes the `get` and provides a simple test for worker-worker communication.

Fix `get` call in worker-to-worker establishment MPI Transport

---

docs/examples/02-broadcast.jl
docs/examples/03-reduce.jl
docs/examples/04-sendrecv.jl
docs/make.jl
docs/src/comm.md
docs/src/environment.md
docs/src/functions.md
docs/src/installation.md
docs/src/installing.md
src/MPI.jl
src/comm.jl
src/environment.jl

Tweak printing in examples to stop lines being interleaved, expand environment and communicator docs, add external links.

Improve docs

---

src/environment.jl

Should return a Cint instead of a Cvoid

use correct signature for MPI_Finalize

---

src/datatypes.jl

The MPI function `Type_Create_Subarray` assumes zero-based indexing, but this was not specified in the original docs  I wrote for this function a while ago. This PR simply clarifies the documentation.

clarify docs

---

src/pointtopoint.jl
test/test_sendrecv.jl

Tests included. Addresses comments in #234. Docs coming. One question is how to properly type the `sendtype` and `recvtype` argument.

add `sendrecv` wrapper

---

docs/src/pointtopoint.md
src/pointtopoint.jl
test/test_sendrecv.jl

Since it is a mutating operation.
cc: @gasagna

Change Sendrecv to Sendrecv!

---

docs/src/functions.md

There are several mentions of "Fortran Function"s in the docs, which are now changed to C functions

Change "Fortran Function" => "C Function" in docs

---

docs/src/pointtopoint.md
src/pointtopoint.jl

Found out about them from issue #308 as I was hoping to send and receive some named tuples so they were useful. But I noticed that they weren't showing up in the documentation so this PR adds a couple of docstrings and adds these functions to `pointtopoint.md`.
I think it might also be useful to spend a paragraph explaining what can be sent and received using which functions. From my understanding:
MPI functions expect arrays of MPI data types (simple C data types only). And if you want to send anything else you must either define your own MPI data type (not sure how to do this) or serialize the object you want to send (which `MPI.send` and `MPI.recv` do for you).

Document `MPI.send` and `MPI.recv`

---

docs/make.jl
docs/src/collective.md
docs/src/functions.md
src/collective.jl
src/datatypes.jl
src/deprecated.jl
test/test_allreduce.jl
test/test_gather.jl
test/test_gatherv.jl
test/test_reduce.jl
test/test_scatter.jl
test/test_scatterv.jl

- Remove explicit `XXX_in_place!` functions, in favour of adding methods to existing mutating functions where behaviour is consistent across all ranks (e.g. `Reduce!`) or requiring branches where root behaviour is special (e.g. `Gather!`/`Scatter!`).
- Make checks and functions more consistent
- Improve docs, move to their own page

Update collective operations

---

Project.toml
deps/consts_msmpi.jl
deps/gen_consts.jl
docs/src/advanced.md
src/MPI.jl
src/buffers.jl
src/collective.jl
src/cuda.jl
src/datatypes.jl
src/deprecated.jl
src/onesided.jl
src/operators.jl
src/pointtopoint.jl
test/test_datatype.jl
test/test_sendrecv.jl
test/test_subarray.jl

This contains two related changes:
1. Defines a specific `Buffer` type, which contains the reference to the storage buffer, its count and datatype. This allows us to simplify the type signatures of various functions, as `count` and `datatype` no longer need to be arguments to the functions. This also adds default conversion methods for `Array`s and `Subarray`s (creating the derived datatypes where necessary, and determining the appropriate `count`s), and moves the point-to-point operations to use these conversions.
2. Improves the handling of `Datatype` handles, by making them garbage-collected objects (like other MPI handles), moves lower-level functions to a submodule, defines consistent interfaces. Also fixes #327.
I still need to move the collective calls over as well, however that …

Add Buffer type, improve Datatype handling

---

deps/consts_msmpi.jl
deps/gen_consts.jl
docs/make.jl
docs/src/io.md
src/MPI.jl
src/collective.jl
src/comm.jl
src/datatypes.jl
src/error.jl
src/handle.jl
src/info.jl
src/io.jl
src/onesided.jl
src/operators.jl
src/pointtopoint.jl
test/test_io.jl

This exposes some of the MPI I/O operations, at the moment only the explicit offset ones.
Also adds an MPIError type to print informative error messages.

Wrap some MPI I/O operations

---

deps/build.jl
docs/make.jl
src/deprecated.jl
test/runtests.jl

To prepare for switching to use BinaryBuilder-provided binaries (#328/#339), this deprecates `mpiexec` so that we can make it consistent. I've renamed it to `mpiexec_path`.

Deprecate mpiexec binding

---

deps/build.jl

Apparently something that happened to PyMPI as well
https://bitbucket.org/mpi4py/mpi4py/issues/63/cant-import-mpi-with-spectrum-mpi
I suspect I didn't see this on Summit before, because we were using the cmake
infrastructure.

Spectrum MPI is called mpi_ibm

---

docs/make.jl
docs/src/knownissues.md
src/MPI.jl

The underlying issue is now fixed in UCX 1.7.0 and later, so we can disable these hooks for now. I've added a known issues section to the docs, and included this there.

Remove UCX environment variables from __init__, document in knownissues.md

---

docs/src/assets/logo.svg

Based on the MPI logo (https://github.com/mpi-forum/mpi-forum.github.io/blob/master/images/mpi-forum-logo.jpg) but using Julia colours.

Add logo to docs

---

src/environment.jl
test/runtests.jl
test/test_error.jl

For my simple test-case this seems to work, of course if any more complicated finalizer clobbers
the current exception we are back at a deadlock. 
x-ref: https://github.com/JuliaLang/julia/issues/35981
```
➜  ~ mpirun -np 2 julia mpi.jl
rank = 0
rank = 1
ERROR: LoadError: Goodbye
Stacktrace:
[1] main() at /home/vchuravy/mpi.jl:11
[2] top-level scope at /home/vchuravy/mpi.jl:16
in expression starting at /home/vchuravy/mpi.jl:16
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
signal (15): Terminated
in expression starting at /home/vchuravy/mpi.jl:16
unknown function …
```

only finalize in the case that jl_current_exception is unset

---

src/collective.jl
test/test_exscan.jl

* Fixed several issues related to the Exscan! API and implementation (one ambiguity, double call to `Op(opfunc, eltype(buf))`, together with the typos described in
https://github.com/JuliaParallel/MPI.jl/issues/394
* Added two tests to test_exscan.jl in order to stress two untested
overloaded variants of Exscan.

Several fixes to `Exscan!`

---

docs/src/io.md
src/io.jl
test/test_io_subarray.jl

This PR adds wrappers to MPI functions for reading and writing to views using independent and collective communication.
In particular, these functions allow to read and write subarrays representing discontiguous views of a distributed array.
Wrapped functions:
- `MPI_File_read`: read from file view (non-collective)
- `MPI_File_read_all`: read from file view (collective)
- `MPI_File_write`: write to file view (non-collective)
- `MPI_File_write_all`: write to file view (collective)

I/O: add wrappers for reading and writing to views

---

src/environment.jl

Fix https://github.com/JuliaParallel/MPI.jl/issues/430. If somebody has a non-OpenMPI/MPICH implementation lying around and can post `mpiexec julia -e 'display ENV'` we can possibly support more.

Warn if wrong MPI

---

docs/src/advanced.md
docs/src/usage.md
src/comm.jl
src/datatypes.jl
src/environment.jl
src/info.jl
src/io.jl
src/onesided.jl
src/operators.jl
src/pointtopoint.jl
src/topology.jl

This seems much simpler, and makes it easy to work with externally-initialized MPI (https://github.com/omlins/libdiffusion/pull/2).

remove reference counting in lieu of Finalized() checks

---

deps/build.jl
src/implementations.jl

This is an alternative to #450 that only uses global symbols on unix systems.
@lyon-fnal would you be able to try this out?

use global symbols on Unix to support LD_PRELOAD interception

---

src/implementations.jl

This PR works around #455 by adding an exception when calling `MPI_Get_library_version` via `ccall` on Unix-like systems, when using Julia versions older than 1.5.
Closes #455.

Avoid InitError on Julia 1.3 with system MPI libraries

---

src/pointtopoint.jl
test/test_sendrecv.jl

Not sure if this is a good change but I thought it would be nice if `MPI.Waitall!` didn't error when `reqs` is an empty array.
This is useful when you're filtering out MPI requests from an array containing other things, e.g. KernelAbstractions.jl events, and you end up with an array with no `MPI.Request`s.
Returning an empty array seemed like reasonable behavior.

Allow `Waitall!` for an empty input `reqs = []`

---

src/datatypes.jl

Adding a finalizer to the `Datatype` in `create_struct` fixes #459 
Please let me know if this is the correct fix.

Add finalizer to `create_struct`

---

deps/consts_microsoftmpi.jl
deps/consts_mpich.jl
deps/consts_openmpi.jl
deps/gen_consts.jl
docs/src/advanced.md
src/MPI.jl
src/environment.jl
src/errorhandler.jl
test/test_errorhandler.jl

add basic error handler functionality

---

docs/src/onesided.md
src/buffers.jl
src/onesided.jl

I hope I understood what these functions do well enough :-)

docstrings for one-sided operations

---

.drone.jsonnet
.drone.yml

With CPUs like A64FX, `aarch64` is an interesting platform for HPC.  I think
it'd be good to tests `MPI.jl` works here.  I just ran the tests on Isambard 2
and they are successful.
However, I have a small application which I tried to run on a MacBook M1
(`aarch64-apple-darwin`) and it crashes at
https://github.com/JuliaLang/julia/blob/58ffe7e3ed3a93a9d816097548e785284f57fbd4/src/codegen.cpp#L5531-L5536
in a call to `MPI.Reduce!`.  Tests are successful also here, so perhaps they
don't capture this error (or the error lies somewhere else), but I'll need to
produce a minimal working example to get a useful test out of it.
If you want to go on with this one, someone will need to enable this repository
at https://cloud.drone.io/.
---
*Edit*: regarding the error I got, I'm using a custom …

Run CI on aarch64 with Drone

---

Project.toml

`Pkg` is already present in the main environment and this causes a warning when
running the tests in Julia v1.8:
```
(jl_H7V8sZ) pkg> test MPI
Testing MPI
┌ Warning: Could not use exact versions of packages in manifest, re-resolving
└ @ Pkg.Operations ~/repo/julia/usr/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1497
┌ Warning: Dependency graph not a DAG, linearizing anyway
└ @ Pkg.Operations ~/repo/julia/usr/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:840
┌ Warning: Dependency graph not a DAG, linearizing anyway
└ @ Pkg.Operations ~/repo/julia/usr/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:840
┌ Warning: Dependency graph not a DAG, linearizing anyway
└ @ Pkg.Operations ~/repo/julia/usr/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:840
┌ Warning: Dependency graph not a DAG, …
```

Remove `Pkg` from test environment

---

bin/mpiexecjl
test/mpiexecjl.jl

[`JULIA_BINDIR`](https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_BINDIR)
is a standard Julia environment variable pointing to the directory where the
`julia` binary is present.
Fix #476.  CC: @ViralBShah.

[mpiexecjl] Accept `JULIA_BINDIR` as environment variable

---

Project.toml
docs/src/environment.md
src/deprecated.jl
src/environment.jl
test/test_threads.jl

add nice init function

---

src/collective.jl

Noticed that the signature is wrong when taking a look at https://juliaparallel.github.io/MPI.jl/latest/collective/#MPI.Scatterv!.

fix Scatterv! function signature in docstring

---

docs/src/advanced.md
docs/src/collective.md
docs/src/onesided.md
docs/src/pointtopoint.md
src/collective.jl
src/datatypes.jl
src/environment.jl
src/nonblocking.jl

In the documentation there are currently plenty of missing docstrings and broken references in docstrings, see for example: https://juliaparallel.github.io/MPI.jl/dev/pointtopoint/
I tried to fix all issues and add to documentation all functions with docstrings.  Please double check I didn't mess up anything, and also that I didn't add docstrings you didn't want to show in the docs.  Now building the documentation locally gives me only a couple of innocuous warnings about `DocTestSetup` being already set.
_Edit_: see the clean log when building the documentation: https://github.com/JuliaParallel/MPI.jl/runs/4217747616?check_suite_focus=true#step:4:1

Various fixes to documentation

---

src/environment.jl

The error message issued when the requested and provided thread levels
do not match refers to an undefined variable `requested`.  Change this
to `threadlevel`.
This fixes an error I ran into
```
┌ Error: Exception while generating log record in module MPI at /mnt/lustre/space/nkm1020/.julia/packages/MPI/biSVL/src/environment.jl:96
│   exception =
│    UndefVarError: required not defined
│    Stacktrace:
│     [1] macro expansion
│       @ ./logging.jl:340 [inlined]
│     [2] Init(; threadlevel::Symbol, finalize_atexit::Bool, errors_return::Bool)
│       @ MPI ~/.julia/packages/MPI/biSVL/src/environment.jl:96
│     [3] Init()
│       @ MPI ~/.julia/packages/MPI/biSVL/src/environment.jl:82
│     [4] top-level scope
│       @ ~/UltraDark.jl/benchmarks/time_step/time_step.jl:27
│     [5] …
```

fix typo in initialization error message

---

.github/workflows/Documenter.yml
.github/workflows/ShellCheck.yml
.github/workflows/UnitTests.yml

This avoids spawning dozens of jobs when modifying unrelated files (like README,
documentation, etc...)
This is related to #529, as we can have a CI job to test only MPIABI.jl,
although we'll probably want to run downstream MPI.jl tests when MPIABI.jl is
modified.

Run CI only when relevant directories are modified

---

docs/src/knownissues.md

Add infos about memory pool to prevent CUDA-aware MPI to fail on multi-GPU nodes and some good practice to check whether CUDA-aware MPI is functional by proposition of @vchuravy. I'd happy to modify this initial draft upon suggestions to enhance content.

Add CUDA-aware MPI hints to known issues documentation.

---

test/test_shared_win.jl

I was unsure whether using `@test_deprecated` or just using the new syntax, but
I thought it may make sense to still test the deprecated function while we keep
it, to make sure it isn't somehow accidentally broken.

Silence warning about deprecated function when running tests

---

docs/examples/07-rma_active.jl
docs/examples/08-rma_passive.jl
docs/make.jl

Adds one-sided communication (active and passive RMA) examples to the docs. Building the docs worked locally. Feel free to suggest improvements to the examples or stylistic changes.
PS: I have more instructive examples like sending a subpart of a matrix via 1) views 2) explicitly using derived types etc. Should I prepare / add those as well? What do you think?

Add RMA examples to docs 

---

.buildkite/pipeline.yml
test/runtests.jl

- [DroneCI] Develop MPIPreferences
- remove old gitlab config
- also run CI against release- branches

Add buildkite CI

---

test/runtests.jl

Ref: https://github.com/JuliaParallel/MPI.jl/issues/539#issuecomment-1039798163.  The idea is to not make tests hard-fail on custom error handlers with unknown ABIs, since it's known that they may not be implemented.  @simonbyrne what do you think about this?  With this change, tests of `MPI.jl` v0.19.2 are successful on Fugaku with system (Fujitsu) MPI, albeit with a broken test.

Do not hard fail in `test_errorhandler.jl` with unknown implementations

---

lib/MPIPreferences/src/MPIPreferences.jl

Diff easier to read if disabling whitespace changes.
Ref: https://github.com/JuliaParallel/MPI.jl/issues/560#issuecomment-1102221341.

[MPIPreferences] Always set `ZES_ENABLE_SYSMAN=1` when dlopening libmpi

---

README.md

[mpi4py.scipy.org](http://mpi4py.scipy.org/) doesn't seem to work anymore.  I'm undecided between https://github.com/mpi4py/mpi4py/ and the documentation at https://mpi4py.readthedocs.io/, but decided to use the GitHub link because the page on [PyPi](https://pypi.org/project/mpi4py/) indicates this one as homepage.

Update link to mpi4py project

---

.gitignore

Do not ignore files that were previously generated by the build step, ~and the
`LocalPreferences.toml` (we shouldn't have to manually set the preference inside
this environment)~.

Cleanup `.gitignore`

---

src/MPI.jl
src/consts/consts.jl

Yet another potential solution to #587. This appears to avoid early dlopen-ing of the library.
Thoughts @giordano @vchuravy @sloede ?

Call constant init via invokelatest

---

docs/src/configuration.md
lib/MPIPreferences/src/MPIPreferences.jl
src/consts/consts.jl
src/consts/mpt.jl

The MPT ABI is based on `mpi.h` and `mpio.h` for MPT v2.23.
cc @jblaschke

Add ABI support for HPE's MPT and HMPT implementations

---

Project.toml
docs/src/reference/library.md
lib/MPIPreferences/Project.toml
lib/MPIPreferences/src/MPIPreferences.jl
src/environment.jl
src/implementations.jl
src/operators.jl
test/runtests.jl
test/test_allreduce.jl
test/test_reduce.jl

We basically moved the detection of ABI/implementation to `MPIPreferences`, and
added only there the support for new ABIs/implementations, which means that
`MPI.identify_implementation` is now giving incorrect results for them, and also
the constants `MPI.MPI_LIBRARY` and `MPI.MPI_LIBRARY_VERSION` are now wrong.
By having a new helper function in `MPIPreferences` we can have all other
functions use it under the hood and keep everything in-sync.
---
***Note***: this is still incomplete, because now `MPI.identify_implementation` returns a string instead of an instance of the enum `MPI.MPIImpl` (which is incomplete because it's missing the new implementations Fujitsu MPI and HPE MPT).  What we should do about that?  Make `MPI.identify_implementation` return a string or create a mapping …

Base `MPI.identify_implementation` on helper function in `MPIPreferences`

---

src/consts/openmpi.jl

Make the code more portable by using corresponding C aliases instead of Julia types.
Xref: https://github.com/JuliaParallel/MPI.jl/issues/576#issue-1213221198, https://github.com/JuliaParallel/MPI.jl/issues/576#issuecomment-1140498016
CC @simonbyrne

Use corresponding aliases for C types in OpenMPI ABI file

---

docs/src/usage.md

I'm porting my `Fortran - MPI` codes to `Julia`, and the first thing that comes to my mind is _how do I write `MPI` aware tests for my package(s) ?_
I couldn't find anything relevant in the docs searching with keywords such as `test` or `runtests.jl`, so this is a proposal to enhance / standardize the docs (to be discussed !).

docs: add note on how to write `MPI` tests

---

src/comm.jl

This is currently rendered incorrectly at https://juliaparallel.org/MPI.jl/dev/reference/comm/#MPI.Comm_remote_group because of the wrong indentation.

Fix indentation of `Comm_remote_group` docstring

---

docs/src/reference/environment.md
src/environment.jl
test/test_test.jl

I spent most of the time deciding where to put the test and the docstring.  I'm not sure I found sensible places, suggestions are welcome.
Fix #624.

Wrap `MPI_Get_processor_name` function

---

docs/src/usage.md
test/common.jl

Update ROC queue initialisation syntax to latest to fix AMDGPU related tests. Follow-up from https://github.com/JuliaParallel/MPI.jl/pull/626#issuecomment-1244468308
Also includes doc updates previously contained in #621

Fix AMDGPU `synchronize` in tests & update doc

---

docs/src/configuration.md
docs/src/reference/mpipreferences.md
lib/MPIPreferences/src/MPIPreferences.jl

add _format key to MPIPreferences

---

src/nonblocking.jl

There is no need for the `struct` to be mutable when the `struct` field are containers.

no need for mutable struct with container fields

---

src/pointtopoint.jl

As far as I can tell, these arguments were completely removed in #329, but the
docstring was still mentioning them.

Remove outdated references to {send,recv}{type,count} in `Sendrecv!` docstring

---

docs/make.jl
docs/src/reference/environment.md
docs/src/reference/misc.md
src/MPI.jl
src/environment.jl
src/misc.jl
test/test_misc.jl
test/test_test.jl

Following up from https://github.com/JuliaParallel/MPI.jl/pull/632#issuecomment-1250138261, @plessl found a system where `MPI.Get_processor_name()` doesn't indeed match `gethostname()`.  I guess we don't want tests to fail for this trivial issue, so I simplified the test to just check that the function returns a string, as suggested in https://github.com/JuliaParallel/MPI.jl/pull/630#discussion_r973322003.  Not super informative, but at least we still make sure the function runs and doesn't crash.
Also, following [mpi4py docs](https://mpi4py.readthedocs.io/en/stable/mpi4py.MPI.html#functions), I moved `MPI.Get_processor_name` to a new "Misc" section (also in source code, and tests).  I think that better classifies this function, and it was also my main doubt in …

Move `Get_processor_name` to new Misc section, and fix test

---

.github/workflows/Documenter.yml
.github/workflows/ShellCheck.yml
.github/workflows/UnitTests.yml

`MPI.jl` test suite is pretty big, and frequent pushes to PRs create a looong queue of jobs, which GitHub Actions kindly doesn't cancel by default.  This lets us clean up the queue automatically.  We're already doing it for invalidations: https://github.com/JuliaParallel/MPI.jl/blob/a9fbfc96208547d8c142ea44eb6a947fd6c79ef7/.github/workflows/Invalidations.yml#L6-L10

[CI] Cancel old jobs if there are new commits on same branch

---

docs/make.jl
docs/src/reference/api.md
gen/Project.toml
gen/src/MPIgenerator.jl
src/auto_generated_api.jl

Fix https://github.com/JuliaParallel/MPI.jl/issues/651.
```julia
julia> using MPI
help?> MPI.API.MPI_Wait
MPI_Wait(request, status)
•  MPI_Wait man page https://www.mpich.org/static/docs/latest/www3/MPI_Wait.html
```
Needs https://github.com/JuliaInterop/Clang.jl/pull/386.

add auto-generated doc links

---

docs/src/reference/advanced.md
src/datatypes.jl
test/test_datatype.jl

https://www.mpich.org/static/docs/v3.3/www3/MPI_Type_create_hvector.html.
https://github.com/eschnett/MPItrampoline/blob/1b759d1f4255b507d2dbbd41a822a27558f5ba2d/mpiabi/mpi_functions.py#L355.

add `create_hvector` (support `MPI_Type_create_hvector`)

---

docs/src/configuration.md
docs/src/knownissues.md

* Consistently suggest to use the `--project` flag (it was already used in some places)
* Fix indentation of code blocks in lists, so that they are rendered correctly
* Do not use Pkg REPL API, which is not recommended for scripting usage
* Use `MPIPreferences.use_system_binary` instead of `MPI.use_system_binary` (which doesn't even exist)

[docs] Minor fixes to configuration instructions

---

.github/workflows/Invalidations.yml

This avoids running some useless jobs when editing, for example, only documentation.

[CI] Limit running invalidations to PRs which touch source code

---

test/test_io_shared.jl

At the moment this only creates noise in tests.
Pros of skipping this:
* we'd get more reliable CI,
* the issue is tracked in #555 anyway, so we know this should be addressed at some point
Cons:
* constant failures may be a reminder to eventually fix the issue, and we'd lose that reminder

Skip flaky test on Windows

---

.github/workflows/Invalidations.yml
Project.toml
docs/src/reference/mpipreferences.md
lib/MPIPreferences/Project.toml
lib/MPIPreferences/src/MPIPreferences.jl
src/MPI.jl

Currently call `@warn` if the MPI implementation has changed: in general I don't like using `@warn` unless something is bad.
Instead it will now use `@info` to print the information, but throws an error if MPI is already loaded, or is loaded subsequently.
It also modifies the message from #641 to be a warning (since that presumably _is_ bad).

[MPIPreferences] add functions to check (and error) if the MPI implementation has changed

---

src/datatypes.jl
test/test_datatype.jl

I did run into out of memory problems, first when I used MPI.Get (which I fixed by reusing always the same Buffer) and later also in Alltoall calls. This happens when derived datatypes are used in those calls, and the MPI.Datatype constructor is called implicitly, like in this example:
```
using MPI
struct Derived
val::Int64
end    
MPI.Init()
comm = MPI.COMM_WORLD
size = MPI.Comm_size(comm)
rank = MPI.Comm_rank(comm)
send_counts = Vector{Cint}(1:size)
recv_counts = fill(Cint(rank+1), size)
send_vals = collect(Iterators.flatten([1:i for i = 1:size])) 
send_vals = map(Derived, send_vals)
A = Array{Derived}(send_vals)
C = Array{Derived}(undef, sum(recv_counts))
while true
MPI.Alltoallv!(VBuffer(A,send_counts), VBuffer(C,recv_counts), comm)
end
MPI.Finalize()
```
This PR fixes this problem, …

cache the created Datatypes

---

src/onesided.jl

The Intel MPI (2018.6.288) implementation returns in Win_shared_query invalid pointers in the case that the array on the owner_rank has length 0. In this case Win_shared_query should create an empty Array of type $T, but unsafe_wrap checks that the alignment of the return pointer is correct, which is now not always the case as the pointer is just uninitialized memory.  
So this pull request checks the returned length, and calls unsafe_wrap only when the length is greater then zero.

check for length 0 in Win_shared_query

---

docs/src/reference/collective.md
src/collective.jl
test/test_bcast.jl

Introduces `Bcast` to complement `Bcast!`. Similar to `Send(obj, ...)` the new variant is useful to directly broadcast objects, scalars in particular, to all ranks without having to introduce buffers or the like.
The usecase that made me create this PR is as simple as `Bcast(1.23, ...)` or `Bcast(p, ...)` where `p` is an instantiation of a struct, say:
```julia
struct Params
a::Float64
b::Float64
n::Int64
end
```
Before the PR, one had to wrap these objects manually into `Ref`s to then use `Bcast!(Ref(obj),...)`. This automates this process (and special cases arrays, where we'll simply make a copy, and `Ref` input objects).

Broadcasting without a bang

---

lib/MPIPreferences/Project.toml
lib/MPIPreferences/src/system.jl

An error thrown during `__init__` makes the package unusable, leaving users
without the possibility to easily reset the preferences.  With this change it is
possible to change the preferences if something goes wrong while loading the
package.
This situation can happen when switching between different MPI implementations in an existing environment, if loading the modules for the new MPI library makes the previous one unloadable.

[MPIPreferences] Make package usable if libmpi can't be loaded

---

src/buffers.jl

An easy fix to #688.
cc @eschnett @giordano

remove Char from MPIDatatypes

---

docs/src/knownissues.md

Mention new problem with HCOLL, and make it clear that custom operators don't work on ARM architecture either.

[docs] Expand known issues

---

gen/Project.toml
src/api/generated_api.jl
src/api/microsoftmpi.jl
src/api/mpich.jl
src/api/mpitrampoline.jl
src/api/mpt.jl
src/api/openmpi.jl
test/test_errorhandler.jl

Change function pointers to function prototypes

---

src/datatypes.jl
src/environment.jl

See https://github.com/JuliaParallel/MPI.jl/issues/684#issuecomment-1358065609
cc @giordano

add finalize hooks to cleanup datatypes

---

docs/src/reference/pointtopoint.md
src/pointtopoint.jl
test/test_matched.jl

Add matched probe/receive operations. Discussed in #681

add matched recv functions

---

docs/src/reference/comm.md

This seems to be missing from the docs ([discourse](https://discourse.julialang.org/t/how-can-i-pass-the-pointer-of-mpi-communicator-to-c-function/87070)).

document how to pass MPI.Comm objects to C

---

docs/src/reference/topology.md
src/topology.jl
test/test_neighbor_comm.jl

This patch adds `MPI.Dist_graph_neighbors` as a convenience wrapper around `MPI.Dist_graph_neighbors_count` and `MPI.Dist_graph_neighbors!` that allocates the required result vectors automatically.
See https://github.com/JuliaParallel/MPI.jl/pull/703#discussion_r1072834691.

Add MPI.Dist_graph_neighbors

---

test/runtests.jl
test/test_spawn.jl

This was already done in https://github.com/JuliaParallel/MPI.jl/blob/6cb0fb07d0105f0017fd393d24d92aa35ddc0b89/test/mpiexecjl.jl#L24 but not in a couple of other places.  Fix #708.  CC @KristofferC

Do not load start up file when running tests

---

docs/src/reference/topology.md
src/topology.jl
test/test_neighbor_comm.jl

This is a slight tweak to #707 use `MPI.UNWEIGHTED` instead of `nothing` (as that is what is used in the constructors).
Also simplifies the code so that the mutating versions return the same as the allocating.
cc @fredrikekre

simplify topology code, use MPI.UNWEIGHTED instead of nothing

---

src/MPI.jl

On my system, I get the following results.
Current `master`:
```
$ julia --project=. -e 'import Pkg; Pkg.precompile(); @time @eval using MPI'
Precompiling project...
1 dependency successfully precompiled in 3 seconds. 13 already precompiled.
0.068064 seconds (60.26 k allocations: 4.630 MiB, 51.31% compilation time)
```
This PR:
```
$ julia --project=. -e 'import Pkg; Pkg.precompile(); @time @eval using MPI'
Precompiling project...
1 dependency successfully precompiled in 3 seconds. 13 already precompiled.
0.038507 seconds (57.11 k allocations: 4.375 MiB, 6.25% compilation time)
```

some explicit precompile statements and precompile-friendly loadtime hooks

---

lib/MPIPreferences/Project.toml
lib/MPIPreferences/src/MPIPreferences.jl

I currently get
```
julia> MPI.MPI_LIBRARY_VERSION_STRING
"MPICH Version:      4.1.1\nMPICH Release date: Mon Mar  6 14:14:15 CST 2023\nMPICH ABI:          15:0:3\nMPICH Device:       ch3:nemesis\nMPICH configure:    --prefix=/workspace/destdir --build=x86_64-linux-musl --host=x86_64-linux-gnu --enable-shared=yes --enable-static=no --with-device=ch3 --disable-dependency-tracking --enable-fast=all,O3 --docdir=/tmp --mandir=/tmp --disable-opencl\nMPICH CC:           cc    -DNDEBUG -DNVALGRIND -O3\nMPICH CXX:          c++   -DNDEBUG -DNVALGRIND -O3\nMPICH F77:          gfortran   -O3\nMPICH FC:           gfortran   -O3\n"
julia> MPI.MPI_LIBRARY_VERSION
v"0.0.0"
```
They are apparently using spaces instead of a tab now, `\s+` should catch both cases. With this patch I get
```
julia> …
```

Fix regex matching MPICH version number

---

.github/workflows/UnitTests.yml

`ubuntu-18.04` isn't supported anymore in GitHub Actions, we aren't running Intel MPI CI jobs at all at the moment.
Opening as draft to see whether this works, because the comments say "20.04 not supported".

[CI] Run Intel MPI jobs on `ubuntu-latest`

---

Project.toml

Will be required to support the merge of https://github.com/JuliaGPU/AMDGPU.jl/pull/423 which requires a minor version bump.

Bump AMDGPU compat

---

docs/src/external.md
docs/src/reference/advanced.md
docs/src/reference/environment.md
src/environment.jl
src/errhandler.jl

Fixes #746. Possibly supersedes #747.

Document external MPI initialization

---

Project.toml
docs/src/reference/collective.md
src/collective.jl
test/test_gather.jl

Hi,
I implemented an arbitrary-data convenience version of `Gather` for my own project and wanted to make a pull request just in case there is interest for adding it to MPI.jl.
Please let me know if there are any ways I can improve it.

Implement automatically serializing `gather`

---

docs/src/reference/collective.md
src/collective.jl
test/test_scatter.jl

Thanks for merging the `gather` pull request! I went ahead and implemented `scatter` as well!
The current version does a tiny amount of unnecessary work by serializing `objs[root + 1]`, which is never sent. I figured saving this might not be worth the additional complexity. Happy to implement it that way though.

Implement automatically serializing `scatter`

---

.gitignore
Project.toml
ext/AMDGPUExt.jl

This PR fixes a bug introduced with a recent update of AMDGPU.jl

Fix ROCm-aware MPI extension

---

docs/src/reference/pointtopoint.md
src/nonblocking.jl
test/test_cooperative_wait.jl

A first implementation of non-blocking wait as discussed in #762

Add non-blocking wait

---

test/test_cooperative_wait.jl

In the cooperative wait test multiple threads are calling MPI functions in a non-serialized way. Thus, MPI needs to be initialized with `threadlevel=:multiple`.

Init cooperative wait test for multiple threads

---

docs/Project.toml
docs/make.jl

Update docs/make.jl for the recent Documenter 1.0 release.

Docs: update to Documenter v1

---

.github/workflows/UnitTests.yml

This didn't use to be necessary, but probably recent changes in the GitHub Actions runners caused `mpiexec -n 4` to complain about insufficient slots available.

[CI] Oversubscribe in OpenMPI jobs

---

lib/MPIPreferences/Project.toml
lib/MPIPreferences/src/MPIPreferences.jl
lib/MPIPreferences/src/parse_cray_cc.jl

Fixes #779 
tagging @marius311 and @omlins

deal with vendor=cray but no gtl

---

test/runtests.jl

I don't think it's useful to have a constant red mark because of a known issue which is already tracked by a specific ticket (#725).  An attempt to resolve the issue with a suggested fix (#742) didn't work, so we aren't going to have this green in the near future.
PR best reviewed by [skipping whitespace changes](https://github.com/JuliaParallel/MPI.jl/pull/791/files?w=1).

Skip threads tests which are known to fail

---

.github/workflows/UnitTests.yml

Container used for CI updated with https://github.com/JuliaParallel/github-actions-buildcache/compare/4a167b45ccf350b6915fbfe55a3421f8b4a22cb4...972c3fdca5acb661a9a7916bac572f56773b289e to use oneAPI MPI 2021.11.0.  This seems to fix #815.

[CI] Use oneAPI MPI 2021.11.0

---

.github/workflows/UnitTests.yml
lib/MPIPreferences/src/MPIPreferences.jl

I recently started working on a cluster using [MVAPICH version 3.0rc](http://mvapich.cse.ohio-state.edu/static/media/mvapich/quick.html), yet MPIPreferences.jl couldn't correctly detect it as the version string changed. Here is a sample of it, taken from the output of `MPIPreferences.identify_abi("libmpi")`:
```
MVAPICH Version        :	3.0rc
MVAPICH Release date   :	11/09/2023
MVAPICH ABI            :	13:12:1
MVAPICH Device         :	ch4:ucx
MVAPICH configure      :	--prefix=/packages/mvapich/mvapich-3.0rc-ucx CC=gcc CXX=g++ FC=gfortran F77=gfortran --with-device=ch4:ucx --with-ucx=/usr/local/packages/ucx/ucx-git-01192024 --disable-rdma-cm --disable-mcast --enable-fast=O3 --enable-debuginfo --enable-cxx --enable-mpit-pvars=all MPICHLIB_CFLAGS=-Werror=implicit-function-declaration …
```

Detect MVAPICH 3

---

.github/workflows/UnitTests.yml

Without this, in some situations libmpi may not be found by Julia.
This should fix #828.  Close #829.

[CI] Set `DYLD_FALLBACK_LIBRARY_PATH` in tests with Homebrew MPI

---

bin/mpiexecjl
test/mpiexecjl.jl

Should fix #833.  I don't have the time to write tests now though, so opening as draft.  @cohensbw could you please test this?  With this PR I get
```console
% mpiexecjl -np 2 --project julia --color=yes -e 'exit(2)'; echo $?
2
```

[mpiexecjl] Return exit code of the mpiexec process

---

.buildkite/pipeline.yml
src/environment.jl
test/runtests.jl

Since https://github.com/JuliaGPU/buildkite/commit/ed35a7903835c0ee89493898821eca0ec38efefb CUDA agent no longer have a version tag.

CUDA CI no longer has version tag

---

.buildkite/pipeline.yml
Project.toml
test/Project.toml
test/test_allreduce.jl

Address #841 
Superseed #839 wrt AMDGPU compat
Getting ROCm CI back on track

Fix ROCm CI

---

docs/src/knownissues.md
docs/src/reference/library.md
docs/src/usage.md
src/environment.jl
test/test_basic.jl

See https://docs.open-mpi.org/en/main/man-openmpi/man3/MPIX_Query_rocm_support.3.html#mpix-query-rocm-support
Seems to be available from v5 of OpenMPI

Add `has_rocm` for OpenMPI

---

test/mpiexecjl.jl

I don't have a good explanation of why this is necessary, but setting `JULIA_BINDIR`, as it was done in #481 for the other run in the same test set, fixes #857 for me.  My only hypothesis is that this somehow helps Julia find its own libraries, perhaps especially if using juliaup, but honestly I can't tell what's failing without setting `JULIA_BINDIR`.  Also, note that that I don't have problems using `mpiexecjl` normally, the issue reported in #857 appeared only when running the tests.

Set `JULIA_BINDIR` when running `mpiexecjl` tests

---

src/MPI.jl

OpenMPI docs are hosted on a new website, and the docs for all the `*_c` functions are not available for that this MPI library.  Also, MPICH docstrings are available at the moment for most functions only in the v4.0 website, not v4.1+.  Extracted out of #856.

Fix autogenerated links to OpenMPI/MPICH docs

---

docs/examples/05-job_schedule.jl
docs/src/configuration.md
docs/src/knownissues.md

a replacement pull for #852 (Closed)

link updates

---

.github/workflows/CompatHelper.yml

This PR enables CompatHelper to watch the `Project.toml` file located in the `test` subdir.

Add subdirs in CompatHelper

---

.github/workflows/CompatHelper.yml
.github/workflows/Documenter.yml
.github/workflows/Invalidations.yml
.github/workflows/UnitTests.yml

Unclear why Dependabot fails to update this workflow.

[GHA] Update `julia-actions/setup-julia` to v2

---

src/datatypes.jl
test/test_datatype.jl

Also:
* skip test of custom primitive type of size 80 on 32-bit systems in Julia v1.12+, as the MPI extent doesn't match Julia's aligned size
* add a test for a new primitive datatype larger than 64 bits which should work on 32-bit systems
With this PR, on a 32-bit linux I get
```julia-repl
julia> using MPI
julia> MPI.Init();
julia> primitive type Primitive80 80 end
julia> MPI.Datatype(Primitive80)
ERROR: AssertionError: The MPI extent of type Primitive80 (12) does not match the size expected by Julia (16)
Stacktrace:
[1] MPI.Datatype(::Type{Primitive80})
@ MPI ~/.julia/packages/MPI/FiDGt/src/datatypes.jl:171
[2] top-level scope
@ REPL[4]:1
```
which should be better than silently getting incorrect results at runtime.
Fix #853.
@simonbyrne @vchuravy can you see cases where the consistency …

Always ensure consistency of new MPI datatypes

---

docs/src/configuration.md

Closes https://github.com/JuliaParallel/MPI.jl/issues/837.

Document how to use MPItrampoline

---

src/pointtopoint.jl

Hi, this is an update of the `MPI.Irecv!` docstring, where the outdated reference to the argument `data` has been replaced by the new argument name, `recvbuf`. Grammar has also been improved.
Will close #894 
Lines 346, 352, 380, and 385 were automatically formatted by my VSCode. If those changes are undesired, I can revert them.
Thank you

Irecv! Docstring Fix

---

Project.toml
test/Project.toml

This PR updates compat entries for AMDGPU 2.0 breaking release for both MPI project and test subfolder.
Note that the patch bump was already done so I left things to 0.20.23.

Update AMDGPU compat
